### ISSUE TITLE
access to the site only to certain users specified in the group

### ISSUE THREAD

**Issue by Arthur-1983** [nickw444/flask-ldap3-login#124]
Good afternoon. Tell me how you can restrict access to the site only to certain users specified in the group? I specified the LDAP_GROUP_DN parameter but it doesn't help

**Comment by gmacon** [comment]
That's out of scope for flask-ldap3-login, which is about authentication, not authorization.

When you call `authenticate`, the return value has an attribute `user_groups` which contains info about each group the user is a member of, and that's as far as this library goes. Your application can use that information however you want, which includes deciding to reject the user if you want to.

**Comment by Arthur-1983** [comment]
Tell me, then what is LDAP_GROUP_DN used for? If authorization in AD is used by users

**Comment by gmacon** [comment]
The LDAP_GROUP_DN is used to figure out what objects are groups; so it might be `dc=org,dc=example,ou=Groups` or something like that.
