### ISSUE TITLE
Active Directory connection not possible

### ISSUE THREAD

**Issue by ribx** [nickw444/flask-ldap3-login#21]
I am testing the connection to a Samba based AD. SIMPLE auth mechanism is disabled by default by samba.

When I try to use SASL, I receive an error, because no mechanism ('sasl_mechanism=') is given to the Connection object of the ldap3 module.

Am I doing something wrong? What is the best way to connect to an Active Directory Server?

**Comment by nickw444** [comment]
I've only ever required a use case against open source Linux implementations of LDAP, if you're up for it, I'm willing to accept a pull request adding this functionality to the library

**Comment by nickw444** [comment]
@ribx did you end up making any progress with getting this library functional in your use-case?

**Comment by ribx** [comment]
Yes, I did. While samba was fine with SSL + Plain Auth, Windows pefered NTLM Auth, which is also encrypted. But I later went to the ldap3 package, because I needed some more information flask-ldap3-login did not provide (mainly Groupinformations).
