### ISSUE TITLE
example code for Custom TLS Context missing

### ISSUE THREAD

**Issue by coreybrett** [nickw444/flask-ldap3-login#24]
the following example codes are the same 

http://flask-ldap3-login.readthedocs.io/en/latest/quick_start.html#basic-scripting-usage-without-a-flask-app

http://flask-ldap3-login.readthedocs.io/en/latest/quick_start.html#custom-tls-context

**Comment by nickw444** [comment]
Thanks for reporting that. Just pushed a fix to master 👍
