### ISSUE TITLE
Users with different "sub OUs" not able to log in

### ISSUE THREAD

**Issue by gigglearrows** [nickw444/flask-ldap3-login#30]
I want two users to log in from 2 different sub OUs.

For example if I want both these 2 to authenticate
user1 dn: OU=Users,OU=subgroup1,OU=group1,OU=Users
user2 dn: OU=Users,OU=subgroup2,OU=group1,OU=Users

it doesnt work because I need the entire user DN in the config. 
e.g `config['LDAP_USER_DN'] = "OU=Users,OU=subgroup1,OU=group1,OU=Users"`

Any way to work around this or perhaps fix it in a later patch?

**Comment by gigglearrows** [comment]
Never mind. Got it to work. Changed LDAP_USER_SEARCH_ATTR or something like that to SUBTREE instead of the default of LEVEL. And the user string to OU=group1,OU=Users

**Comment by nickw444** [comment]
Perfect, glad to see you got it working 👍
