### ISSUE TITLE
LDAP and local accounts

### ISSUE THREAD

**Issue by keans** [nickw444/flask-ldap3-login#31]
I am using the module in combination with the sqlalchemy module. As far as I can see it is not possible to have LDAP as well as local users. Is it planned or am I missing something?

**Comment by nickw444** [comment]
This is definitely possible - I have done this in many projects. I.e. having local _root_ privilege users.

You can do this by providing a custom Login Form. See [forms.py](https://github.com/nickw444/flask-ldap3-login/blob/b3e5515bca52d3ac45b93cb4de5fe868216f4fd3/flask_ldap3_login/forms.py) - it provides `LDAPLoginForm`. You can either make your own, or create a subclass of this to provide the custom validation.

Your best bet here would be to do something like:

```python
from flask_ldap3_login.forms import LDAPLoginForm
from flask_wtf import FlaskForm

class MyAuthForm(LDAPLoginForm):
    def validate(self,  *args, **kwargs):
        valid = FlaskForm.validate(self, *args, **kwargs)
        if not valid:
            print("Form validation failed")
            return valid
        if self.username.data == 'root' and self.password.data == 'mycoolpassword':
            // TODO: Replace this with a call to your users datastore.
            return True

        return super().validate(*args, **kwargs)
```

**Comment by keans** [comment]
Thanks for the reply. Yes, I also thought about overwriting the form, but I thought that is a common desire that could be implemented as part of the module. Anyways, I will try your suggestion...

**Comment by nickw444** [comment]
I aim to keep this module as use-case agnostic as possible to allow it to be as flexible as possible and work for the masses.

**Comment by nickw444** [comment]
Closing this issue out for now, if you have any other problems feel free to reply or open another issue.
