### ISSUE TITLE
import users from LDAP

### ISSUE THREAD

**Issue by coreybrett** [nickw444/flask-ldap3-login#59]
I currently have this extension working for login to my app.

When someone authenticates, they are added to my app's database using their LDAP GUID as an id.

How could I pre-populate the database with all my LDAP accounts?

**Comment by nickw444** [comment]
Hi @coreybrett , thanks for raising the issue. 

> How could I pre-populate the database with all my LDAP accounts?

You will need to write a script which pulls information down from your LDAP server using the [connection exposed from the library](https://flask-ldap3-login.readthedocs.io/en/latest/API.html#flask_ldap3_login.LDAP3LoginManager.connection). You can use this connection to query the directory and in your script you can iterate over the results of your query to create records in your database.

Also, just a side note: after a long internal debate, I have made the difficult decision that I will no longer be actively maintaining this repo. I am now in the process of finding a new maintainer - if this is something that may interest you, you can find more details in the [README](https://github.com/nickw444/flask-ldap3-login#maintainer-wanted)
