### ISSUE TITLE
Cannot integrate OpenLDAP

### ISSUE THREAD

**Issue by RenditionInfosec** [nickw444/flask-ldap3-login#60]
We currently swapped providers from MS Active Directory to OpenLDAP and now I cannot get it to connect. Everything is the same from the hierarchy to the creds being used to the server name. 

Where can I find documentation on integration with OpenLDAP or is it not currently possible?

**Comment by nickw444** [comment]
Hi @RenditionInfosec, thanks for raising the issue. After a long internal debate, I have made the difficult decision that I will no longer be actively maintaining this repo. I am now in the process of finding a new maintainer - if this is something that may interest you, you can find more details in the [README](https://github.com/nickw444/flask-ldap3-login#maintainer-wanted)

**Comment by nickw444** [comment]
> Where can I find documentation on integration with OpenLDAP or is it not currently possible?

And to quickly answer your question because it's a simple one - I have previously used this library with OpenLDAP. In fact, the entire library was developed against OpenLDAP, not MS active directory.

**Comment by HeMan** [comment]
@RenditionInfosec You have to set `app.config["LDAP_GROUP_OBJECT_FILTER"] = "(objectclass=posixGroup)"` or `app.config["LDAP_GROUP_OBJECT_FILTER"] = "(objectclass=groupOfNames)"` depending on how you have defined your groups in your directory.

**Comment by HeMan** [comment]
Or, if you don't need groups you could add `app.config["LDAP_SEARCH_FOR_GROUPS"] = False`

**Comment by HeMan** [comment]
I think this issue is resolved. I'll close it, you could add a new issue if you still have problem.
