### ISSUE TITLE
Only cn attribute is working

### ISSUE THREAD

**Issue by Litchfield-TWOSE** [nickw444/flask-ldap3-login#69]
I'm recording this as an issue as I do not know where else to turn.

For context, I'm coding this against a Windows 2012 R2 Active Directory server.  I am also using the sample application to get it working, before implementing it into my application.

I have this working as long as I set LDAP_USER_RDN_ATTR and LDAP_USER_LOGIN_ATTR to 'cn'.  If I set it to 'sAMAccountName', then I only ever get 'Invalid Username/Password.

Any suggestions or recommendations on how I can get this code to recognize anything else other than the 'cn' attribute in AD?

Thank you in advance!!

**Comment by Litchfield-TWOSE** [comment]
I figured out the issue, and it was a coding mistake on my side.  I will close this

**Comment by gmacon** [comment]
This could be an indication that our documentation is incomplete or unclear. Can you share with us what went wrong and how you fixed it? If you identified a problem with the docs, feel free to point that out, too.
