### ISSUE TITLE
Drop support for Python 2.7

### ISSUE THREAD

**Issue by gmacon** [nickw444/flask-ldap3-login#71]
Upstream support for Python 2 will end on January 1, 2020, about four months from now.

Downloads from PyPI of flask-ldap3-login in the last 30 days:

| python_version | download_count |
| -------------- | -------------- |
| 3.7            |          1,132 |
| 3.6            |            942 |
| 3.5            |            914 |
| 2.7            |            541 |
| 3.4            |            123 |
| Total          |          3,652 |

**Comment by hugovk** [comment]
Please see PR #74.
