### ISSUE TITLE
DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired

### ISSUE THREAD

**Issue by ciobancai** [nickw444/flask-ldap3-login#75]
Hi,

After updating the Flask / Flask-WTF and WTForms i receive the following warning

```
2019-10-08 15:28:30,129 - INFO -  * Restarting with stat MainThread
/usr/local/lib/python3.7/site-packages/flask_wtf/recaptcha/widgets.py:5: DeprecationWarning: The import 'werkzeug.url_encode' is deprecated and will be removed in Werkzeug 1.0. Use 'from werkzeug.urls import url_encode' instead.
  from werkzeug import url_encode
/usr/local/lib/python3.7/site-packages/flask_ldap3_login/forms.py:26: DeprecationWarning: Required is going away in WTForms 3.0, use DataRequired
  username = wtforms.StringField('Username', validators=[validators.Required()])
```

If you think to fix it and to release a new build.

**Comment by gmacon** [comment]
We should find out what version of WTForms introduced the DataRequired validator and set a minimum version requirement on that version.

**Comment by brandon-sling** [comment]
https://wtforms.readthedocs.io/en/stable/changes.html#version-1-0-2
looks like version 1.0.2 split the Required into DataRequired and InputRequired.
Also per lots of posts I've read while looking into it, the FlaskForm should use InputRequired not DataRequired.
DataRequired could return false if, for example, a 0 was entered.

**Comment by northwestwitch** [comment]
Hi! WTForms v3.0 has been released yesterday and this became a big I'm afraid.

**Comment by nickw444** [comment]
Hey @northwestwitch, I've released a pre-release, [0.9.17b1](https://pypi.org/project/flask-ldap3-login/0.9.17b1/). Could you please try this out? (`pip install flask-ldap3-login==0.9.17b1`). If it appears to work as expected, I'll proceed to release it as a full release.

**Comment by nickw444** [comment]
Great to hear, I'll put out a mainline release this evening. Thanks for testing and confirming @northwestwitch

**Comment by nickw444** [comment]
0.9.17 is now live on Pypi. `pip install flask-ldap3-login==0.9.17`
