### ISSUE TITLE
LDAP_GROUP_OBJECT_FILTER Docs and code disagree

### ISSUE THREAD

**Issue by cakiwi** [nickw444/flask-ldap3-login#8]
LDAP_GROUP_OBJECT_FILTER

flask-ldap3-login/docs/source/configuration.rst 
Defaults to '(objectclass=groupOfUniqueNames)'

https://github.com/nickw444/flask-ldap3-login/blob/master/flask_ldap3_login/__init__.py#L131
self.config.setdefault('LDAP_GROUP_OBJECT_FILTER', '(objectclass=group)')

**Comment by nickw444** [comment]
Thanks for pointing this out. I'll update the documentation to state `objectclass=group`
